name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]  # Adjust if you want a different branch

jobs:
  build-and-publish:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/porla:latest
          build-args: |
            GITVERSION_SEMVER=1.0.0
            CCACHE_REMOTE_STORAGE=http://ccache.porla.org/cache|read-only|connect-timeout=500
